config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'clients#index'
  resources :clients do
    resources :contacts
    collection do
      post :bulk_insert
      post :import
    end
  end
end

app/models/act_cat.rb
class ActCat < ActiveHash::Base
  self.data=[
    {id: 1,category: '見積'},
    {id: 2,category: '訪問'},
    {id: 3,category: '来社'},
    {id: 4,category: 'DM'},
    {id: 5,category: '展示会来場'}


  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :client_rank
  belongs_to_active_hash :client_cat
  belongs_to_active_hash :closing_day
  belongs_to_active_hash :payment_day
  belongs_to_active_hash :payment_method


  belongs_to :user
  has_many :contacts

  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_MOBILE_REGEX=/\A[0]+[789]+[0]\d{8}\z/
  validates :client_name1,presence: true
  validates :email,format: {with: VALID_EMAIL_REGEX,message: 'メールアドレスが正しくありません。'},allow_blank: true
  validates :mobile,format: {with: VALID_MOBILE_REGEX,message: '携帯電話番号が正しくありません。'},allow_blank: true
  def self.import(file)
    CSV.foreach(file.path,headers: true) do |row|
      client = find_by(id: row["id"]) || new
      client.attributes = row.to_hash.slice(*updatable_attributes)
      client.save
    end
  end
  def self.updatable_attributes
    ["id","cleint_name1","client_name2","user_id"]
  end


end

app/models/client_cat.rb
class ClientCat < ActiveHash::Base
  self.data=[
    {id: 1,category: '代理店販売'},
    {id: 2,category: '直販'}
  ]
end

app/models/client_rank.rb
class ClientRank < ActiveHash::Base
  self.data=[
    {id: 1,rank: 'Aランク'},
    {id: 2,rank: 'Bランク'},
    {id: 3,rank: 'Cランク'}
  ]
end

app/models/closing_day.rb
class ClosingDay < ActiveHash::Base
  self.data=[
    {id: 5,closing_day: '5日'},
    {id: 10,closing_day: '10日'},
    {id: 15,closing_day: '15日'},
    {id: 20,closing_day: '20日'},
    {id: 25,closing_day: '25日'},
    {id: 30,closing_day: '末日'},
    {id: 99,closing_day: '都度'}
  ]
end

app/models/contact.rb
class Contact < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :act_cat
  
  belongs_to :client
end

app/models/payment_day.rb
class PaymentDay < ActiveHash::Base
  self.data=[
    {id: 5,payment_day: '当月5日'},
    {id: 10,payment_day: '当月10日'},
    {id: 15,payment_day: '当月15日'},
    {id: 20,payment_day: '当月20日'},
    {id: 25,payment_day: '当月25日'},
    {id: 30,payment_day: '当月末日'},
    {id: 105,payment_day: '翌月5日'},
    {id: 110,payment_day: '翌月10日'},
    {id: 115,payment_day: '翌月15日'},
    {id: 120,payment_day: '翌月20日'},
    {id: 125,payment_day: '翌月25日'},
    {id: 130,payment_day: '翌月末日'},
    {id: 205,payment_day: '翌々月5日'},
    {id: 210,payment_day: '翌々月10日'},
    {id: 215,payment_day: '翌々月15日'},
    {id: 220,payment_day: '翌々月20日'},
    {id: 225,payment_day: '翌々月25日'},
    {id: 230,payment_day: '翌々月末日'},
    {id: 999,payment_day: '都度'}
  ]
end

app/models/payment_method.rb
class PaymentMethod < ActiveHash::Base
  self.data=[
    {id: 1,name: "現金"},
    {id: 2,name: "小切手"},
    {id: 3,name: "手形"}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clients

  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,presence: true,uniqueness: true,format: {with: VALID_EMAIL_REGEX,message: 'メールアドレスが正しくありません。'}
  validates :password,presence: true, length: {minimum: 6}
  validates :name,presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action -> {set_client(params[:id])},only: [:show,:edit,:update,:destroy]
  def index
    @clients=Client.where(user_id: current_user.id).where(["client_name1 LIKE ? OR client_name2 LIKE ?", "%#{params[:client_search]}%","%#{params[:client_search]}%"])
    @client=Client.new
    @in_progress_contacts=Contact.joins(:client).where(clients: {user_id: current_user.id}).where(in_progress: true).order("end_date ASC")
    @finished_contacts=Contact.joins(:client).where(clients: {user_id: current_user.id}).where(in_progress: false)
    @contact = Contact.new
  end
  def create
    @client =Client.create(client_params)
    redirect_to root_path
  end
  def show
    @contact = Contact.new
    @contacts = @client.contacts
  end
  def edit
  end
  def update
    @client.update(client_params)
    redirect_to client_path(params[:id])
  end
  def bulk_insert
    contact_array=[]
    bulk_params[:client_ids].each do |cid|
      contact=Contact.new(act_cat_id: bulk_params[:act_cat_id],detail: bulk_params[:detail],start_date: bulk_params[:start_date],end_date: bulk_params[:end_date],in_progress: bulk_params[:in_progress],client_id: cid)
      contact_array << contact
    end
    Contact.import contact_array
    redirect_to clients_path
  end
  def import
    Client.import(params[:file])
    redirect_to clients_path
  end

  private
  def set_client(params)
    @client = Client.find(params)
  end
  def client_params
    params.require(:client).permit(:client_name1,:client_name2,:postcode,:add1,:add2,:add3,:tel,:fax,:client_person_in_charge,:mobile,:url,:email,:client_rank_id,:client_cat_id,:closing_day_id,:payment_day_id,:payment_method_id,:user_id)
    # params.require(:client).permit(:company_name1,:company_name2,:postcode,:addr1,:addr2,:addr3,:tel,:fax,:client_person_in_charge,:mobile,:url,:email,:client_rank_id,:client_cat_id,:closing_day_id,:payment_day_id,:payment_method_id,:user_id,contacts_attributes:[:id,:act_cat_id,:detail,:file,:start_date,:end_date,:in_progress])
  end
  def bulk_params
    params.require(:contact).permit(:act_cat_id,:detail,:start_date,:end_date,:in_progress,{:client_ids => []})
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    Contact.create(contact_params)
    redirect_to client_path(params[:client_id])
  end
  def edit
    @contact = Contact.find(params[:id])
    @client = @contact.client
  end
  def update
    @contact = Contact.find(params[:id])
    @client = @contact.client
    @contact.update(contact_params)
    redirect_to client_path(params[:client_id])
  end

  private
  def contact_params
    params.require(:contact).permit(:act_cat_id,:detail,:start_date,:end_date,:in_progress).merge(client_id: params[:client_id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/clients/_contacts.html.haml
.main.show
  .main-header
    .main-title
      コンタクト情報
    .form-btn.form-btn__contact.js-modal-open
      コンタクトを新規追加
  .main-contents
    %table
      %tbody.striped#in_progress-search-result
        - @contacts.each do |contact|
          %tr
            %td
              .column-btn
                = link_to '編集', edit_client_contact_path(contact.client.id,contact)
            %td.main-column
              %p
                =contact.in_progress ? "進行中" : "完了"; + " 期間：" + contact.start_date.strftime("%Y-%m-%d") + "~" + contact.end_date.strftime("%Y-%m-%d")

                -# = contact.in_progress ? "進行中" : "完了" + "  期間：" + contact.start_date.strftime("%Y-%m-%d") + "~" + contact.end_date.strftime("%Y-%m-%d")
              %p
                = contact.client.client_name1 + contact.client.client_name2
              %p
                ="カテゴリ：" + contact.act_cat.category if contact.act_cat_id
              %p
                =contact.detail

app/views/clients/_csv.html.haml
.main-header
  .main-title
    CSVインポート
.main-contents
  .form
    = form_with url: import_clients_path,local: true do |f|
      = f.file_field :file ,id: "import_csv"
      .form-btn__csv
        = f.submit "インポート"
.main-header
  .main-title
    CSVエクスポート
.main-contents
  .form
    %p
      ファイルをエクスポート
    .form-btn__csv
      = link_to "エクスポート",clients_path(format: :csv),class: "form-btn__csv"

app/views/clients/_main-client.html.haml
.main-header
  .main-title
    顧客検索
  .search
    = form_with url:clients_path,local: true do |f|
      = f.text_field :client_search,id: "client_search",class: 'search-box',placeholder: '会社名で検索'
.main-contents
  %table
    %tbody.striped#client-search-result
      - @clients.each do |client|
        %tr.column
          %td
            .column-btn
              = link_to '詳細',client_path(client.id)
          %td.main-column
            %p
              =client.client_name1 + client.client_name2

app/views/clients/_main-contact-register-at-once.html.haml
.main-header
  .main-title
    コンタクト一括登録
.main-contents
  .form
    =form_with model:@contact, url:bulk_insert_clients_path,local: true do |f|
      .input-field
        = f.label 'カテゴリ', for: "act_cat"
        = f.collection_select :act_cat_id, ActCat.all, :id, :category, {include_blank: true},{id: "act_cat"}
      .input-field
        = f.label '詳細', for: "detail"
        = f.text_field :detail, id: "detail"
      .input-field
        = f.label '開始日', for: "start_date"
        = f.date_field :start_date, id: "start_date"
      .input-field
        = f.label '終了日', for: "end_date"
        = f.date_field :end_date, id: "end_date"
      .input-field
        = f.label '進行中'
        = f.select :in_progress,[["進行中",1], ["完了",0]],{},{id: "in_progress"}
      .register-wrapper
        .register-list
          .register-list__title
            クライアント一覧
          .register-list__box
            %table
              %tbody#client-list
                - @clients.each do |client|
                  %tr.register-list__element.client-list{data: {id: "#{client.id}",name: "#{client.client_name1+client.client_name2}"}}
                    %td
                      =client.client_name1 + client.client_name2
                    %td
                      →
        .register-list
          .register-list__title
            登録するクライアント
          .register-list__box
            %table
              %tbody#register-list
      = f.submit '登録',class: "form-btn"

app/views/clients/_main-finished.html.haml
.main-header
  .main-title
    完了済
  -# .search
  -#   = form_with url:clients_path,local: true do |f|
  -#     = f.text_field :contact_search,id: "finished_search",class: 'search-box',placeholder: '詳細内容で検索'
.main-contents
  %table
    %tbody.striped#finished-search-result
      - @finished_contacts.each do |contact|
        %tr
          %td
            .column-btn
              = link_to '編集', edit_client_contact_path(contact.client.id,contact)
          %td.main-column
            %p
              =contact.in_progress ? "進行中" : "完了" + " 期間：" + contact.start_date.strftime("%Y-%m-%d") + "~" + contact.end_date.strftime("%Y-%m-%d")
            %p
              = contact.client.client_name1 + contact.client.client_name2
            %p
              ="カテゴリ：" + contact.act_cat.category if contact.act_cat_id
            %p
              =contact.detail

app/views/clients/_main-in_progress.html.haml
.main-header
  .main-title
    進行中
  -# .search
  -#   = form_with url:clients_path,local: true do |f|
  -#     = f.text_field :in_progress_search,id: "in_progress_search",class: 'search-box',placeholder: '詳細内容で検索'
.main-contents
  %table
    %tbody.striped#in-progress-search-result
      - @in_progress_contacts.each do |contact|
        %tr
          %td
            .column-btn
              = link_to '編集', edit_client_contact_path(contact.client.id,contact)
          %td.main-column
            %p
              =contact.in_progress ? "進行中" : "完了"
              =" 期間：" + contact.start_date.strftime("%Y-%m-%d") + "~" + contact.end_date.strftime("%Y-%m-%d")

            %p
              = contact.client.client_name1 + contact.client.client_name2
            %p
              ="カテゴリ：" + contact.act_cat.category if contact.act_cat_id
            %p
              =contact.detail

app/views/clients/_main.html.haml
.main.show#in_progress-search
  =render 'main-in_progress'
.main#finished-search
  =render 'main-finished'
.main#client-search
  = render 'main-client'
.main#contact-register-at-once
  = render 'main-contact-register-at-once'
.main#csv
  = render 'csv'

app/views/clients/_side-client.html.haml
.sidebar
  %h4.collection-title
    顧客情報
  .client-collection
    .client-element
      .client-element__label
        会社名1：
      .client-element__data
        =@client.client_name1
    .client-element
      .client-element__label
        会社名2：
      .client-element__data
        =@client.client_name2
    .client-element
      .client-element__label
        郵便番号：
      .client-element__data
        =@client.postcode
    .client-element
      .client-element__label
        住所1：
      .client-element__data
        =@client.add1
    .client-element
      .client-element__label
        住所2：
      .client-element__data
        =@client.add2
    .client-element
      .client-element__label
        住所3：
      .client-element__data
        =@client.add3
    .client-element
      .client-element__label
        Tel：
      .client-element__data
        =@client.tel
    .client-element
      .client-element__label
        Fax：
      .client-element__data
        =@client.fax
    .client-element
      .client-element__label
        顧客担当者：
      .client-element__data
        =@client.client_person_in_charge
    .client-element
      .client-element__label
        携帯番号：
      .client-element__data
        =@client.mobile
    .client-element
      .client-element__label
        URL：
      .client-element__data
        =@client.url
    .client-element
      .client-element__label
        Email：
      .client-element__data
        =@client.email
    .client-element
      .client-element__label
        顧客ランク：
      .client-element__data
        =@client.client_rank.rank if @client.client_rank_id
    .client-element
      .client-element__label
        顧客区分：
      .client-element__data
        =@client.client_cat.category if @client.client_cat_id
    .client-element
      .client-element__label
        締日：
      .client-element__data
        =@client.closing_day.closing_day if @client.closing_day_id
    .client-element
      .client-element__label
        支払日：
      .client-element__data
        =@client.payment_day.payment_day if @client.payment_day_id
    .client-element
      .client-element__label
        支払方法：
      .client-element__data
        =@client.payment_method.name if @client.payment_method_id
    .client-element
      .client-element__label
        自社担当者：
      .client-element__data
        =@client.user.name
    .form-btn.form-btn__edit
      =link_to '編集',edit_client_path(params[:id])

app/views/clients/_sidebar.html.haml
.sidebar
  .collection
    .collection-title
      HOME
    .collection-item.home.active.orange
      進行中
    .collection-item.home
      完了済
    .collection-item.home
      顧客検索
  .collection
    .collection-title
      Registration
    .collection-item.js-modal-open
      顧客新規登録
    .collection-item.home
      コンタクト一括登録
    .collection-item.home
      CSVインポート/エクスポート

app/views/clients/edit.html.haml
.wrapper
  .edit-wrapper
    %h4
      顧客情報編集
    = render '/shared/client-form'

app/views/clients/index.html.haml
.wrapper
  = render 'sidebar'
  = render 'main'
  .modal.js-modal
    .modal__bg.js-modal-close
    .modal__content
      %h4
        顧客新規登録
      = render '/shared/client-form'

app/views/clients/show.html.haml
.wrapper
  = render 'side-client'
  = render 'contacts'
  .modal.js-modal
    .modal__bg.js-modal-close
    .modal__content
      %h4
        新規コンタクト
      = render '/shared/contact-form'

app/views/contacts/edit.html.haml
.wrapper
  .edit-wrapper
    %h4
      コンタクト情報編集
    = render '/shared/contact-form'

app/views/layouts/_footer.html.haml
.footer
  CRM-Nekoyashiki - © 2020 Copyright nekoyashiki

app/views/layouts/_header.html.haml
%nav
  .nav-wrapper
    = link_to 'CRM-nekoyashiki',root_path,{class: 'brand-logo'}
    .login_user
      -if user_signed_in?
        .login_user__content
          Login User:
          =current_user.name
        .login_user__content
          =link_to 'Log Out', destroy_user_session_path,method: :delete
      - else
        .login_user__content
          = link_to 'Log In', new_user_session_path
        .login_user__content
          = link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CrmNekoyashiki
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:charset => "UTF-8", :src => "https://yubinbango.github.io/yubinbango/yubinbango.js"}
  %body
    = render '/layouts/header'
    = yield
    = render '/layouts/footer'

app/views/shared/_client-form.html.haml
.form
  = form_for @client,html: {class: "h-adr"} do |f|
    %span.p-country-name{style: "display:none;"}Japan
    .input-field
      = f.label '会社名1',for: 'company1'
      = f.text_field :client_name1 ,id: 'company1'
    .input-field
      = f.label '会社名2',for: 'company2'
      = f.text_field :client_name2 ,id: 'company2'
    .input-field
      = f.label '郵便番号',for: 'postcode'
      = f.text_field :postcode ,id: 'postcode',class: "p-postal-code"
    .input-field
      = f.label '住所1',for: 'addr1'
      = f.text_field :add1,class: "p-region",id: 'addr1'
    .input-field
      = f.label '住所2(町名・番地)',for: 'addr2'
      = f.text_field :add2 ,id: 'addr2',class: "p-locality p-street-address"
    .input-field
      = f.label '住所3(建物名・号室)',for: 'addr3'
      = f.text_field :add3 ,id: 'addr3',class: "p-extended-address"
    .input-field
      = f.label 'Tel',for: 'tel'
      = f.text_field :tel ,id: 'tel'
    .input-field
      = f.label 'Fax',for: 'fax'
      = f.text_field :fax ,id: 'fax'
    .input-field
      = f.label '顧客担当者',for: 'client_person_in_charge'
      = f.text_field :client_person_in_charge ,id: 'client_person_in_charge'
    .input-field
      = f.label '携帯番号',for: 'mobile'
      = f.text_field :mobile ,id: 'mobile'
    .input-field
      = f.label 'URL',for: 'url'
      = f.text_field :url ,id: 'url'
    .input-field
      = f.label 'Email',for: 'email'
      = f.text_field :email ,id: 'email'
    .input-field
      = f.label '顧客ランク',for: 'client-rank'
      = f.collection_select :client_rank_id, ClientRank.all, :id ,:rank,{include_blank: true},{id: "client-rank"}
    .input-field
      = f.label '顧客区分',for: 'client-cat'
      = f.collection_select :client_cat_id, ClientCat.all, :id ,:category,{include_blank: true},{id: "client-cat"}
    .input-field
      = f.label '締日',for: 'closing-day'
      = f.collection_select :closing_day_id, ClosingDay.all, :id ,:closing_day,{include_blank: true},{id: "closing-day"}
    .input-field
      = f.label '支払日',for: 'payment-day'
      = f.collection_select :payment_day_id,  PaymentDay.all, :id ,:payment_day,{include_blank: true},{id: "payment-day"}
    .input-field
      = f.label '支払方法',for: 'payment-method'
      = f.collection_select :payment_method_id, PaymentMethod.all, :id ,:name,{include_blank: true},{id: "payment-method"}
    .input-field
      = f.label '自社担当',for: 'user'
      = f.collection_select :user_id, User.all, :id ,:name,{include_blank: false,selected: current_user.id},{id: "user"}
    = f.submit '登録', class: 'form-btn'
  .form-btn.close
    = link_to'閉じる', root_path,{class: 'form-btn__close'}

app/views/shared/_contact-form.html.haml
.form
  =form_with model:[@client,@contact],local: true do |f|
    .input-field
      = f.label 'カテゴリ', for: "act_cat"
      = f.collection_select :act_cat_id, ActCat.all, :id, :category, {include_blank: true},{id: "act_cat"}
    .input-field
      = f.label '詳細', for: "detail"
      = f.text_field :detail, id: "detail"
    .input-field
      = f.label '開始日', for: "start_date"
      = f.date_field :start_date, id: "start_date"
    .input-field
      = f.label '終了日', for: "end_date"
      = f.date_field :end_date, id: "end_date"
    .input-field
      = f.label '進行中'
      = f.select :in_progress,[["進行中",1], ["完了",0]],{},{id: "in_progress"}
    = f.submit '登録',class: "form-btn"